server:
    undertow:
        io-threads: 2
        worker-threads: 2000
        buffer-size: 1024
        direct-buffers: true
spring:
    application:
        name: hryj-eureka
    profiles:
        active: server
security:
    basic:
        enabled: true
    user:
        name: admin
        password: hryj1866
management:
    security:
        enabled: false
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 60000
logging:
    config: classpath:logback.xml
